(defun color-theme-mine ()
  (interactive)
  (color-theme-install
   '(color-theme-mine
     ((foreground-color . "#505050")
      (cursor-color . "#000000")
      (background-color . "#FFFFFF")
      (background-mode . dark))
     (default ((t (nil))))
     (underline ((t (:underline t))))
     (region ((t (:background "#004080"))))
     (font-lock-builtin-face ((t (:foreground "#151157"))))
     (font-lock-comment-face ((t (:foreground "#C18938" :italic t))))
     (font-lock-function-name-face ((t (:foreground "#6190BE"))))
     (font-lock-keyword-face ((t (:foreground "#393586"))))
     (font-lock-string-face ((t (:foreground "#26B161"))))
     (font-lock-type-face ((t (:foreground "#2B557B" :bold t))))
     (font-lock-variable-name-face ((t (:foreground "#7D5212"))))
     (minibuffer-prompt ((t (:foreground "#0E3051" :bold t))))
     (font-lock-warning-face ((t (:foreground "#FF0000" :bold t))))
     )))
